import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'


export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<div className={styles.grid}>
					<Link href="/demos/facets-hide">
						<a className={styles.card}>
							<h2>Accordion facets with hiding</h2>
							<p>Show accordion facets that hide on click</p>
						</a>
					</Link>

					<Link href="/demos/facets-mount">
						<a className={styles.card}>
							<h2>Accordion facets with mounting</h2>
							<p>Show accordion facets that mount and dismount on click</p>
						</a>
					</Link>

					<Link href="/demos/logo-spin">
						<a className={styles.card}>
							<h2>Logo Spin</h2>
							<p>Show spinning logo</p>
						</a>
					</Link>

					<Link href="/demos/variants">
						<a className={styles.card}>
							<h2>Animation variants</h2>
							<p>Show an example of duplicating animations through variants.</p>
						</a>
					</Link>

					<a
						href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
						className={styles.card}
					>
						<h2>Deploy &rarr;</h2>
						<p>
							Instantly deploy your Next.js site to a public URL with Vercel.
						</p>
					</a>
				</div>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{' '}
					<span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	)
}
