import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'


export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<div className={styles.grid}>
					<Link href="/demos/facets-hide">
						<a className={styles.card}>
							<h2>Accordion facets with hiding</h2>
							<p>Show accordion facets that hide on click</p>
						</a>
					</Link>

					<Link href="/demos/facets-mount">
						<a className={styles.card}>
							<h2>Accordion facets with mounting</h2>
							<p>Show accordion facets that mount and dismount on click</p>
						</a>
					</Link>

					<Link href="/demos/logo-spin">
						<a className={styles.card}>
							<h2>Logo Spin</h2>
							<p>Show spinning logo</p>
						</a>
					</Link>

					<Link href="/demos/layout">
						<a className={styles.card}>
							<h2>Motion layout</h2>
							<p>Show how to animate using framer motion layout</p>
						</a>
					</Link>

					<Link href="/demos/svg-path">
						<a className={styles.card}>
							<h2>SVG Path</h2>
							<p>Animate an SVG path</p>
						</a>
					</Link>

					<Link href="/demos/dock">
						<a className={styles.card}>
							<h2>Dock</h2>
							<p>Animation inspired by macOS dock</p>
						</a>
					</Link>
				</div>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{' '}
					<span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	)
}
